plugins:
  - jest

env:
  browser: true
  es2021: true
extends:
  - airbnb-base
  - plugin:jest/recommended
  - plugin:import/errors
  - plugin:import/warnings
parserOptions:
  ecmaVersion: 13
  sourceType: module
rules:
  no-console: off
  import/prefer-default-export: off
  import/extensions: off
  import/no-named-as-default: off
  consistent-return: off
  import/named: off
  implicit-arrow-linebreak: off
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
